### ISSUE TITLE
When I run ./register.sh , I came up with this problem.

### ISSUE THREAD

**Issue by VolcanoWCAN** [stfbk/AuBACE#1]
I install fabric v1.1.0 ,successlly. And I can start the dockers successfully.
![2020-02-22 12-59-15屏幕截图](https://user-images.githubusercontent.com/33406143/75086843-a53c1680-5573-11ea-81dc-c2cbce3b9413.png)

Then I run npm install, it runs well:
![2020-02-22 12-59-48屏幕截图](https://user-images.githubusercontent.com/33406143/75086846-aa996100-5573-11ea-9520-5d66893675de.png)

However , when I run ./register.sh , I came up with this problem.
Could you please give me some instructions about  how it happens.
The log outputs like this:

Registering Org1 admin identitiy
module.js:550
    throw err;
    ^

Error: Cannot find module './utils.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/volcano/go/src/github.com/hyperledger/fabric/fabric-samples/Healthcare_scenario/node_modules/_fabric-ca-client@1.4.6@fabric-ca-client/lib/FabricCAServices.js:10:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Registering Org1 predefined user identities
module.js:550
    throw err;
![2020-02-22 13-00-25屏幕截图](https://user-images.githubusercontent.com/33406143/75086850-b8e77d00-5573-11ea-94ef-5869f3dd8255.png)

**Comment by caffeine-elemental** [comment]
Hello @VolcanoWCAN!
The error was due to package.json requiring _any_ version of fabric-ca-client _higher than_ 1.1.0, instead of _exactly_ 1.1.0.
However, we have not worked on the 1.1.0 version for a while now. The current master branch has been updated to HF version 1.4-latest, currently 1.4.8. You can find the old v1.1.0 in a separate branch, with the fix applied, but it will not be updated.
Thanks for reporting the issue :) Sorry it took so long to get back to you!
